import os
import sys
from datetime import datetime

import pytz

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "APyB"
copyright = "APyB, 2024"
author = "Associação Python Brasil"
html_baseurl = "https://apyb.python.org.br"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

sys.path.append(os.path.abspath("./_ext"))

extensions = [
    "sphinx.ext.githubpages",
    "sphinx_reredirects",
    "myst_parser",
    # Local extensions
    "github_issues_url",
    "github_repos",
    "template",
]

redirects = {
    "guias/como-organizar-eventos/": "https://apyb.python.org.br/associados/guias/como-organizar-eventos/",
}

myst_enable_extensions = [
    "colon_fence",
]

templates_context = {
    "now": datetime.now(tz=pytz.timezone("America/Sao_Paulo")),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

new_issue_title = "Melhoria na página: {document_path}"
new_issue_body = """
Página: {page_url}
Arquivo: {page_source_url}

---

### Descrição

...
"""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "pt_BR"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

html_extra_path = [os.path.join(os.path.abspath("."), "_files")]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"
html_theme_options = {
    "light_logo": "apyb-light.svg",
    "dark_logo": "apyb-dark.svg",
    "sidebar_hide_name": True,
    "light_css_variables": {
        # Background
        "color-background-secondary": "#FAF9FA",
        # Sidebar
        "color-link-underline": "#FAF9FA",
        "color-link-underline--hover": "#0056CD",
        "color-sidebar-link-text--top-level": "#0056CD",
        # Text
        "color-content-foreground": "#011224",
        "color-link": "#0056cd",
    },
    "dark_css_variables": {
        # Background
        "color-background-border": "#0056CD",
        "color-background-hover": "#01122430",
        "color-background-primary": "#011224",
        "color-background-secondary": "#0056CD",
        # Sidebar
        "color-sidebar-caption-text": "#ffffff",
        "color-sidebar-link-text": "#ffffffaa",
        "color-sidebar-link-text--top-level": "#ffffff",
        "color-sidebar-search-background": "rgba(255, 255, 255, 0.1)",
        "color-sidebar-search-background--focus": "rgba(255, 255, 255, 0.2)",
        "color-sidebar-search-foreground": "#ffffff",
        "color-sidebar-search-icon": "rgba(255, 255, 255, 0.5)",
        # Text
        "color-content-foreground": "#FAF9FAee",
        "color-link": "#fff",
        "color-link--hover": "#FFB93B",
        "color-link-underline": "#FFB93B",
        "color-link-underline--hover": "#FFB93B",
    },
}

html_context = {
    # Extension: github_issues_url
    "source_url": "https://github.com/apyb/wiki",
    "source_branch": "main",
    "source_dir": "source",
    "new_issue_title": new_issue_title,
    "new_issue_body": new_issue_body,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "css/custom.css",
]
html_title = "Associação Python Brasil"
